### ISSUE TITLE
Cannot set redistributionDelay

### ISSUE THREAD

**Issue by lnthai2002** [artemiscloud/activemq-artemis-operator#100]
**Describe the bug**
I tried to set the redistributionDelay to a different value than 0 (default in cluster mode) but got parsing error when deploying:
`java.lang.IllegalStateException: Invalid configuration
        at org.apache.activemq.artemis.utils.XMLUtil.validate(XMLUtil.java:365)
        at org.apache.activemq.artemis.core.config.FileDeploymentManager.readConfiguration(FileDeploymentManager.java:80)
        at org.apache.activemq.artemis.integration.FileBroker.createComponents(FileBroker.java:118)
        at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:113)
        at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:155)
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:103)
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:134)
        at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:50)
Caused by: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'redistribution-delay'. One of '{"urn:activemq:core":dead-letter-address, "urn:activemq:core":auto-create-dead-letter-resources, "urn:activemq:core":dead-letter-queue-prefix, "urn:activemq:core":dead-letter-queue-suffix, "urn:activemq:core":expiry-address, "urn:activemq:core":auto-create-expiry-resources, "urn:activemq:core":expiry-queue-prefix, "urn:activemq:core":expiry-queue-suffix, "urn:activemq:core":expiry-delay, "urn:activemq:core":min-expiry-delay, "urn:activemq:core":max-expiry-delay, "urn:activemq:core":redelivery-delay, "urn:activemq:core":redelivery-delay-multiplier, "urn:activemq:core":redelivery-collision-avoidance-factor, "urn:activemq:core":max-redelivery-delay, "urn:activemq:core":max-delivery-attempts, "urn:activemq:core":max-size-bytes, "urn:activemq:core":max-size-bytes-reject-threshold, "urn:activemq:core":page-size-bytes, "urn:activemq:core":page-max-cache-size, "urn:activemq:core":address-full-policy, "urn:activemq:core":message-counter-history-day-limit, "urn:activemq:core":last-value-queue, "urn:activemq:core":default-last-value-queue, "urn:activemq:core":default-last-value-key, "urn:activemq:core":default-non-destructive, "urn:activemq:core":default-exclusive-queue, "urn:activemq:core":default-group-rebalance, "urn:activemq:core":default-group-rebalance-pause-dispatch, "urn:activemq:core":default-group-buckets, "urn:activemq:core":default-group-first-key, "urn:activemq:core":default-consumers-before-dispatch, "urn:activemq:core":default-delay-before-dispatch, "urn:activemq:core":send-to-dla-on-no-route, "urn:activemq:core":slow-consumer-threshold, "urn:activemq:core":slow-consumer-threshold-measurement-unit, "urn:activemq:core":slow-consumer-policy, "urn:activemq:core":slow-consumer-check-period, "urn:activemq:core":auto-create-jms-queues, "urn:activemq:core":auto-delete-jms-queues, "urn:activemq:core":auto-create-jms-topics, "urn:activemq:core":auto-delete-jms-topics, "urn:activemq:core":auto-create-queues, "urn:activemq:core":auto-delete-queues, "urn:activemq:core":auto-delete-created-queues, "urn:activemq:core":auto-delete-queues-delay, "urn:activemq:core":auto-delete-queues-message-count, "urn:activemq:core":config-delete-queues, "urn:activemq:core":auto-create-addresses, "urn:activemq:core":auto-delete-addresses, "urn:activemq:core":auto-delete-addresses-delay, "urn:activemq:core":config-delete-addresses, "urn:activemq:core":config-delete-diverts, "urn:activemq:core":management-browse-page-size, "urn:activemq:core":management-message-attribute-size-limit, "urn:activemq:core":default-purge-on-no-consumers, "urn:activemq:core":default-max-consumers, "urn:activemq:core":default-queue-routing-type, "urn:activemq:core":default-address-routing-type, "urn:activemq:core":default-consumer-window-size, "urn:activemq:core":default-ring-size, "urn:activemq:core":retroactive-message-count, "urn:activemq:core":enable-metrics, "urn:activemq:core":enable-ingress-timestamp}' is expected.`

**To Reproduce**
1. Deploy a cluster of 2 brokers using the following specs:
`apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  adminUser: root
  adminPassword: password
  deploymentPlan:
    size: 2
    image: placeholder
    messageMigration: true
    persistenceEnabled: true
    podSecurity:
      runAsUser: 0
  console:
    expose: true
    sslEnabled: false
  addressSettings:
    applyRule: merge_all
    addressSetting:
      - match: '#'
        autoDeleteAddresses: true
        autoDeleteQueues: true
        redistributionDelay: 5000`
2. observe the error in the log of the broker pod

**Platform (please complete the following information):**
 - OS: Windows 10 with docker-desktop kubernetes backed by WSL2
 - Version 0.20.0 according to version.go
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by gtully** [comment]
this issue is resolved in the image: see https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/issues/29
