### ISSUE TITLE
Segmentation fault deleting addresses

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#320]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1773882]

goroutine 940 [running]:
github.com/artemiscloud/activemq-artemis-operator/controllers.deleteQueue(0xc0005aa9c0, {{{0xc0007fe8d6?, 0xc0000520f0?}, {0xc00071c618?, 0x0?}}}, {0x1f0daf0, 0xc000112a50}, 0x1f16b28?)
        /home/dbruscin/Workspace/brusdev/artemiscloud/activemq-artemis-operator/controllers/activemqartemisaddress_controller.go:348 +0x5a2
github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisAddressReconciler).Reconcile(0xc00000fcf8, {0x1f07118?, 0xc000cfab10?}, {{{0xc0007fe8d6, 0x7}, {0xc00071c618, 0x15}}})
        /home/dbruscin/Workspace/brusdev/artemiscloud/activemq-artemis-operator/controllers/activemqartemisaddress_controller.go:89 +0xe66
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000b0a9a0, {0x1f07118, 0xc000cfaa50}, {{{0xc0007fe8d6?, 0x1b5cb20?}, {0xc00071c618?, 0x404fb4?}}})
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x27e
...

**Comment by brusdev** [comment]
Resolved in v1.0.7
