### ISSUE TITLE
operator jolokia has hardcoded 2s timeout that is insufficient - leading to errors on the broker when resources are constrained

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#511]
**Describe the bug**
The operator waits 2s  (https://github.com/artemiscloud/activemq-artemis-operator/blob/c4ddc1737d5654ab17782149b14bd1f9cf91822b/pkg/utils/jolokia/jolokia.go#L92) for a response from the brokers jolokia endpoint, which is reasonable but results in ugly stack traces in the broker logs.
The operator could be more patient, and the timeout should be configurable or inferred from the context.
The broker could also be less verbose in its logging in this case. (https://github.com/hawtio/hawtio-java/blob/b684f6eefa346dab508bc22adae8a7e6c0541987/hawtio-system/src/main/java/io/hawt/web/AuthenticationFilter.java#L196)

example of the stack trace on the broker failing to reply...
```
10:10:28 INFO {qtp532613259-52} : Failed to invoke action /read/org.apache.activemq.artemis:broker="amq-broker"/Status due to:
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(AccessController.java:716) ~[?:?]
	at javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
	at io.hawt.web.auth.AuthenticationFilter.executeAs(AuthenticationFilter.java:104) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at io.hawt.web.auth.AuthenticationFilter.lambda$doFilter$0(AuthenticationFilter.java:80) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at io.hawt.system.Authenticator.authenticate(Authenticator.java:151) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at io.hawt.web.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:79) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:46) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.auth.SessionExpiryFilter.process(SessionExpiryFilter.java:107) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at io.hawt.web.auth.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:60) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.apache.activemq.artemis.component.JolokiaFilter.doFilter(JolokiaFilter.java:50) ~[artemis-web-2.28.0.redhat-00001.jar:2.28.0.redhat-00001]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) ~[jetty-security-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) [jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) [jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) [jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) [jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) [jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.11.jar:10.0.11]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:830) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232) ~[jetty-util-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214) ~[jetty-util-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:584) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1060) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1132) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269) ~[?:?]
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:622) ~[?:?]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
	at org.jolokia.util.IoUtil.streamResponseAndClose(IoUtil.java:46) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.sendStreamingResponse(AgentServlet.java:574) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.sendResponse(AgentServlet.java:557) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:369) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:310) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503) ~[jetty-servlet-api-4.0.6.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jetty-servlet-api-4.0.6.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665) ~[?:?]
	at io.hawt.web.auth.LoginRedirectFilter.doFilter(LoginRedirectFilter.java:63) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.auth.AuthenticationFilter.lambda$executeAs$1(AuthenticationFilter.java:105) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	... 68 more
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:217) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:153) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563) ~[?:?]
	at java.nio.channels.SocketChannel.write(SocketChannel.java:642) ~[?:?]
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386) ~[jetty-io-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:830) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232) ~[jetty-util-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214) ~[jetty-util-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:584) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1060) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1132) ~[jetty-server-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269) ~[?:?]
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:622) ~[?:?]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:347) ~[?:?]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169) ~[?:?]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:252) ~[?:?]
	at org.jolokia.util.IoUtil.streamResponseAndClose(IoUtil.java:46) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.sendStreamingResponse(AgentServlet.java:574) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.sendResponse(AgentServlet.java:557) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:369) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:310) ~[jolokia-core-1.7.1.redhat-00001.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503) ~[jetty-servlet-api-4.0.6.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jetty-servlet-api-4.0.6.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665) ~[?:?]
	at io.hawt.web.auth.LoginRedirectFilter.doFilter(LoginRedirectFilter.java:63) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-10.0.11.jar:10.0.11]
	at io.hawt.web.auth.AuthenticationFilter.lambda$executeAs$1(AuthenticationFilter.java:105) ~[hawtio-system-2.0.0.fuse-sb2-7_11_1-00013-redhat-00002.jar:2.0.0.fuse-sb2-7_11_1-00013-redhat-00002]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	... 68 more
```

**Expected behaviour**
this is transient, in normal operation, 2s is reasonable, on startup is can be exceeded. Really the logging on the broker is excessive.

**Comment by gtully** [comment]
adding a custom logger via extra mounts x-logging-config with something like:
```
appender.stdout.name = STDOUT
appender.stdout.type = Console
rootLogger = INFO, STDOUT
logger.tooVerbose.name=io.hawt.web
logger.tooVerbose.level=ERROR
```
will ensure that that info level log message will be suppressed. see https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#configuring-logging-for-brokers

**Comment by gtully** [comment]
the fix is to defer calls to the broker status till we know the broker is up and ready. A precondition to checking the config applied condition is a true deployed condition. This will avoid the scenario where we poke the broker while it is starting. The 2s round trip is ok, a tidy up of the client is on the todo.
