### ISSUE TITLE
Deleting ActiveMQArtemisAddress CR may causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by brusdev** [artemiscloud/activemq-artemis-operator#807]
**Describe the bug**
Sometime, the tests of the context `address queue config defaults` fails with the following error on the test `			It("configurationManaged default should be true (with queue configuration)`:
```
activemq-artemis-operator/controllers/activemqartemisaddress_controller_test.go:128panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b76495]

goroutine 9672 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x1eb33c0, 0x35b0c30})
        /home/dbruscin/sdk/go1.20.13/src/runtime/panic.go:884 +0x213
github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisAddressReconciler).deleteQueue(0xc002d46150, 0xc0060236a8, {{{0xc002895f30?, 0xc0036b2990?}, {0xc003d6ae88?, 0xc00005a128?}}}, {0x252f280, 0xc0036b2990}, 0xc003d6ae88?)
        /home/dbruscin/Workspace/brusdev/artemiscloud/activemq-artemis-operator/controllers/activemqartemisaddress_controller.go:361 +0x855
github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisAddressReconciler).Reconcile(0xc002d46150, {0x0?, 0x0?}, {{{0xc002895f30, 0x4}, {0xc003d6ae88, 0x17}}})
        /home/dbruscin/Workspace/brusdev/artemiscloud/activemq-artemis-operator/controllers/activemqartemisaddress_controller.go:91 +0x390
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x25267f0?, {0x2523730?, 0xc004eaf1a0?}, {{{0xc002895f30?, 0xb?}, {0xc003d6ae88?, 0x0?}}})
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00051b220, {0x2523688, 0xc003b1ea00}, {0x1fa3b20?, 0xc0013a4fc0?})
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316 +0x3ca
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00051b220, {0x2523688, 0xc003b1ea00})
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/dbruscin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x587
FAIL    github.com/artemiscloud/activemq-artemis-operator/controllers   2200.983s
```

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
This fix will be included in 1.1.0
